import type { ExperienceId } from './contextual-experience.data'

export type CustomerProductId = Exclude<ExperienceId, 'invoice-partner'>
export type PaymentAttention = 'overdue' | 'upcoming' | null
export type SettlementMode = 'manual' | 'buyer-payment'
export type PeriodTone = 'status-info' | 'status-live' | 'status-warning' | 'status-danger' | 'status-success' | 'status-neutral'
export type InstalmentStatus = 'paid' | 'upcoming' | 'overdue' | 'scheduled'
export type CustomerFinancingStatus = 'requested' | 'live' | 'overdue' | 'repaid' | 'cancelled' | 'declined'
export type InvoiceUploadOwner = 'client' | 'partner-buyer'

export interface CustomerInstalment {
  label: string
  dueDate: string
  amount: number
  status: InstalmentStatus
}

export interface CustomerFinancingPeriod {
  id: string
  reference: string
  relationshipId: string
  relationshipName: string
  relationshipType: string
  statusKey: CustomerFinancingStatus
  statusLabel: string
  statusTone: PeriodTone
  disbursementDate?: string
  repaymentDueDate: string
  amountFinanced: number
  totalRepaid: number
  outstandingBalance: number
  amountDue: number
  paymentAttention: PaymentAttention
  settlementMode: SettlementMode
  instalments: readonly CustomerInstalment[]
  invoiceType?: string
  invoiceReference?: string
  eligibleReceivables?: number
  availableToWithdraw?: number
  financedDays?: number
  note?: string
}

export interface CustomerRelationship {
  id: string
  name: string
  relationshipType: string
  limitLabel: string
  limit: number
  used: number
  available: number
  periodIds: readonly string[]
  fundsRequestUrl?: string
  fundsRequestEnabled?: boolean
  fundsRequestLabel?: string
  invoiceUploadOwner?: InvoiceUploadOwner
}

export interface CustomerWorkspace {
  id: CustomerProductId
  heading: string
  intro: string
  primaryActionLabel: string
  primaryActionKind: 'request-funds' | 'relationships'
  relationshipNavLabel?: string
  relationshipHeading?: string
  relationshipIntro?: string
  relationshipNoun: string
  availableMetricLabel: string
  availableMetricValue: number
  availableMetricHelper: string
  outstandingMetricLabel: string
  outstandingMetricValue: number
  outstandingMetricHelper: string
  dueMetricLabel: string
  dueActionLabel: string
  dueDateColumnLabel: string
  totalRepaidColumnLabel: string
  outstandingColumnLabel: string
  relationships: readonly CustomerRelationship[]
  periods: readonly CustomerFinancingPeriod[]
}

export const ABF_FUNDS_REQUEST_DEMO_URL = 'https://financing.avenews-gt.com/ishai/form/ABFDemo1/formperma/88hpcsGdZAsMIA0-EbgWUOc6jIqIr5VRd1htmpKqIRA'

export const CUSTOMER_FINANCING_STATUSES: readonly {
  value: CustomerFinancingStatus
  label: string
  tone: PeriodTone
}[] = [
  { value: 'requested', label: 'Requested', tone: 'status-info' },
  { value: 'live', label: 'Live', tone: 'status-live' },
  { value: 'overdue', label: 'Overdue', tone: 'status-danger' },
  { value: 'repaid', label: 'Repaid', tone: 'status-success' },
  { value: 'cancelled', label: 'Cancelled', tone: 'status-neutral' },
  { value: 'declined', label: 'Declined', tone: 'status-danger' },
]

const STATUS_BY_KEY = Object.fromEntries(
  CUSTOMER_FINANCING_STATUSES.map(status => [status.value, status]),
) as Record<CustomerFinancingStatus, (typeof CUSTOMER_FINANCING_STATUSES)[number]>

function financingStatus(statusKey: CustomerFinancingStatus): Pick<CustomerFinancingPeriod, 'statusKey' | 'statusLabel' | 'statusTone'> {
  const status = STATUS_BY_KEY[statusKey]
  return {
    statusKey,
    statusLabel: status.label,
    statusTone: status.tone,
  }
}

const ACL_PERIODS: readonly CustomerFinancingPeriod[] = [
  {
    id: 'acl-requested-0612',
    reference: 'FR-2026-0612',
    relationshipId: 'acl-general',
    relationshipName: 'Avenews',
    relationshipType: 'Agri Credit Line',
    ...financingStatus('requested'),
    repaymentDueDate: '2026-09-30',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    instalments: [],
    note: 'Funds Request submitted and awaiting approval. No financing has been disbursed yet.',
  },
  {
    id: 'acl-live-0318',
    reference: 'FR-2026-0318',
    relationshipId: 'acl-general',
    relationshipName: 'Avenews',
    relationshipType: 'Agri Credit Line',
    ...financingStatus('live'),
    disbursementDate: '2026-06-25',
    repaymentDueDate: '2026-08-25',
    amountFinanced: 1400000,
    totalRepaid: 700000,
    outstandingBalance: 700000,
    amountDue: 700000,
    paymentAttention: 'upcoming',
    settlementMode: 'manual',
    instalments: [
      { label: 'Instalment 1 of 2', dueDate: '2026-07-25', amount: 700000, status: 'paid' },
      { label: 'Instalment 2 of 2', dueDate: '2026-08-25', amount: 700000, status: 'upcoming' },
    ],
  },
  {
    id: 'acl-overdue-0421',
    reference: 'FR-2026-0421',
    relationshipId: 'acl-general',
    relationshipName: 'Avenews',
    relationshipType: 'Agri Credit Line',
    ...financingStatus('overdue'),
    disbursementDate: '2026-07-10',
    repaymentDueDate: '2026-08-10',
    amountFinanced: 500000,
    totalRepaid: 0,
    outstandingBalance: 500000,
    amountDue: 500000,
    paymentAttention: 'overdue',
    settlementMode: 'manual',
    instalments: [
      { label: 'Final repayment', dueDate: '2026-08-10', amount: 500000, status: 'overdue' },
    ],
  },
  {
    id: 'acl-repaid-0201',
    reference: 'FR-2026-0201',
    relationshipId: 'acl-general',
    relationshipName: 'Avenews',
    relationshipType: 'Agri Credit Line',
    ...financingStatus('repaid'),
    disbursementDate: '2026-04-01',
    repaymentDueDate: '2026-06-01',
    amountFinanced: 650000,
    totalRepaid: 650000,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    instalments: [
      { label: 'Instalment 1 of 2', dueDate: '2026-05-01', amount: 325000, status: 'paid' },
      { label: 'Instalment 2 of 2', dueDate: '2026-06-01', amount: 325000, status: 'paid' },
    ],
  },
  {
    id: 'acl-cancelled-0520',
    reference: 'FR-2026-0520',
    relationshipId: 'acl-general',
    relationshipName: 'Avenews',
    relationshipType: 'Agri Credit Line',
    ...financingStatus('cancelled'),
    repaymentDueDate: '2026-09-20',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    instalments: [],
    note: 'Funds Request was cancelled before disbursement.',
  },
  {
    id: 'acl-declined-0528',
    reference: 'FR-2026-0528',
    relationshipId: 'acl-general',
    relationshipName: 'Avenews',
    relationshipType: 'Agri Credit Line',
    ...financingStatus('declined'),
    repaymentDueDate: '2026-09-28',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    instalments: [],
    note: 'Funds Request was declined and no financing was disbursed.',
  },
]

const ABF_PERIODS: readonly CustomerFinancingPeriod[] = [
  {
    id: 'abf-eastleigh-requested',
    reference: 'FR-2026-0819',
    relationshipId: 'abf-eastleigh',
    relationshipName: 'Eastleigh Traders Co.',
    relationshipType: 'Counterparty Supplier',
    ...financingStatus('requested'),
    repaymentDueDate: '2026-10-19',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceType: 'Unpaid Invoice',
    invoiceReference: 'INV-ET-3301',
    instalments: [],
    note: 'Supplier-scoped Funds Request submitted and awaiting approval.',
  },
  {
    id: 'abf-quickmart-live',
    reference: 'FR-2026-0422',
    relationshipId: 'abf-quickmart',
    relationshipName: 'Quick Mart Stores',
    relationshipType: 'Counterparty Supplier',
    ...financingStatus('live'),
    disbursementDate: '2026-06-22',
    repaymentDueDate: '2026-08-22',
    amountFinanced: 380000,
    totalRepaid: 190000,
    outstandingBalance: 190000,
    amountDue: 190000,
    paymentAttention: 'upcoming',
    settlementMode: 'manual',
    invoiceType: 'Unpaid Invoice',
    invoiceReference: 'INV-QM-2042',
    instalments: [
      { label: 'Instalment 1 of 2', dueDate: '2026-07-22', amount: 190000, status: 'paid' },
      { label: 'Instalment 2 of 2', dueDate: '2026-08-22', amount: 190000, status: 'upcoming' },
    ],
  },
  {
    id: 'abf-naivas-overdue',
    reference: 'FR-2026-0407',
    relationshipId: 'abf-naivas',
    relationshipName: 'Naivas Fresh Produce',
    relationshipType: 'Counterparty Supplier',
    ...financingStatus('overdue'),
    disbursementDate: '2026-07-07',
    repaymentDueDate: '2026-08-07',
    amountFinanced: 459000,
    totalRepaid: 0,
    outstandingBalance: 459000,
    amountDue: 459000,
    paymentAttention: 'overdue',
    settlementMode: 'manual',
    invoiceType: 'Fully Paid Invoice',
    invoiceReference: 'INV-NV-1128',
    instalments: [
      { label: 'Final repayment', dueDate: '2026-08-07', amount: 459000, status: 'overdue' },
    ],
  },
  {
    id: 'abf-quickmart-repaid',
    reference: 'FR-2026-0124',
    relationshipId: 'abf-quickmart',
    relationshipName: 'Quick Mart Stores',
    relationshipType: 'Counterparty Supplier',
    ...financingStatus('repaid'),
    disbursementDate: '2026-01-24',
    repaymentDueDate: '2026-03-24',
    amountFinanced: 260000,
    totalRepaid: 260000,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceType: 'Unpaid Invoice',
    invoiceReference: 'INV-QM-1884',
    instalments: [
      { label: 'Instalment 1 of 2', dueDate: '2026-02-24', amount: 130000, status: 'paid' },
      { label: 'Instalment 2 of 2', dueDate: '2026-03-24', amount: 130000, status: 'paid' },
    ],
  },
  {
    id: 'abf-naivas-cancelled',
    reference: 'FR-2026-0712',
    relationshipId: 'abf-naivas',
    relationshipName: 'Naivas Fresh Produce',
    relationshipType: 'Counterparty Supplier',
    ...financingStatus('cancelled'),
    repaymentDueDate: '2026-10-12',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceType: 'Unpaid Invoice',
    invoiceReference: 'INV-NV-1295',
    instalments: [],
    note: 'Funds Request was cancelled before disbursement.',
  },
  {
    id: 'abf-eastleigh-declined',
    reference: 'FR-2026-0730',
    relationshipId: 'abf-eastleigh',
    relationshipName: 'Eastleigh Traders Co.',
    relationshipType: 'Counterparty Supplier',
    ...financingStatus('declined'),
    repaymentDueDate: '2026-10-30',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceType: 'Unpaid Invoice',
    invoiceReference: 'INV-ET-3274',
    instalments: [],
    note: 'Funds Request was declined and no financing was disbursed.',
  },
]

const STF_PERIODS: readonly CustomerFinancingPeriod[] = [
  {
    id: 'stf-greenharvest-requested',
    reference: 'FR-2026-0820',
    relationshipId: 'stf-greenharvest',
    relationshipName: 'GreenHarvest Distributors',
    relationshipType: 'Partner Supplier',
    ...financingStatus('requested'),
    repaymentDueDate: '2026-10-20',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'GH-INV-9012',
    instalments: [],
  },
  {
    id: 'stf-greenharvest-live',
    reference: 'FR-2026-0501',
    relationshipId: 'stf-greenharvest',
    relationshipName: 'GreenHarvest Distributors',
    relationshipType: 'Partner Supplier',
    ...financingStatus('live'),
    disbursementDate: '2026-06-01',
    repaymentDueDate: '2026-08-30',
    amountFinanced: 300000,
    totalRepaid: 150000,
    outstandingBalance: 150000,
    amountDue: 150000,
    paymentAttention: 'upcoming',
    settlementMode: 'manual',
    invoiceReference: 'GH-INV-8831',
    instalments: [
      { label: 'Instalment 1 of 2', dueDate: '2026-07-30', amount: 150000, status: 'paid' },
      { label: 'Instalment 2 of 2', dueDate: '2026-08-30', amount: 150000, status: 'upcoming' },
    ],
  },
  {
    id: 'stf-meru-overdue',
    reference: 'FR-2026-0415',
    relationshipId: 'stf-meru',
    relationshipName: 'Meru Agrovets Ltd',
    relationshipType: 'Partner Supplier',
    ...financingStatus('overdue'),
    disbursementDate: '2026-07-15',
    repaymentDueDate: '2026-08-15',
    amountFinanced: 240000,
    totalRepaid: 0,
    outstandingBalance: 240000,
    amountDue: 240000,
    paymentAttention: 'overdue',
    settlementMode: 'manual',
    invoiceReference: 'MA-INV-5519',
    instalments: [
      { label: 'Final repayment', dueDate: '2026-08-15', amount: 240000, status: 'overdue' },
    ],
  },
  {
    id: 'stf-seedco-repaid',
    reference: 'FR-2026-0218',
    relationshipId: 'stf-seedco',
    relationshipName: 'SeedCo Kenya',
    relationshipType: 'Partner Supplier',
    ...financingStatus('repaid'),
    disbursementDate: '2026-03-18',
    repaymentDueDate: '2026-06-18',
    amountFinanced: 510000,
    totalRepaid: 510000,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'SC-INV-9201',
    instalments: [
      { label: 'Instalment 1 of 3', dueDate: '2026-04-18', amount: 170000, status: 'paid' },
      { label: 'Instalment 2 of 3', dueDate: '2026-05-18', amount: 170000, status: 'paid' },
      { label: 'Instalment 3 of 3', dueDate: '2026-06-18', amount: 170000, status: 'paid' },
    ],
  },
  {
    id: 'stf-meru-cancelled',
    reference: 'FR-2026-0711',
    relationshipId: 'stf-meru',
    relationshipName: 'Meru Agrovets Ltd',
    relationshipType: 'Partner Supplier',
    ...financingStatus('cancelled'),
    repaymentDueDate: '2026-10-11',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'MA-INV-5590',
    instalments: [],
  },
  {
    id: 'stf-seedco-declined',
    reference: 'FR-2026-0731',
    relationshipId: 'stf-seedco',
    relationshipName: 'SeedCo Kenya',
    relationshipType: 'Partner Supplier',
    ...financingStatus('declined'),
    repaymentDueDate: '2026-10-31',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'SC-INV-9310',
    instalments: [],
  },
]

const INF_PERIODS: readonly CustomerFinancingPeriod[] = [
  {
    id: 'inf-twiga-requested',
    reference: 'DP-2026-10-15-TWIGA',
    relationshipId: 'inf-twiga',
    relationshipName: 'Twiga Foods Ltd',
    relationshipType: 'Partner Buyer',
    ...financingStatus('requested'),
    repaymentDueDate: '2026-10-15',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'buyer-payment',
    eligibleReceivables: 720000,
    availableToWithdraw: 320000,
    instalments: [],
    note: 'A Funds Request has been submitted from this Dynamic Period and is awaiting approval.',
  },
  {
    id: 'inf-twiga-live',
    reference: 'DP-2026-09-15-TWIGA',
    relationshipId: 'inf-twiga',
    relationshipName: 'Twiga Foods Ltd',
    relationshipType: 'Partner Buyer',
    ...financingStatus('live'),
    disbursementDate: '2026-08-17',
    repaymentDueDate: '2026-09-15',
    amountFinanced: 850000,
    totalRepaid: 0,
    outstandingBalance: 850000,
    amountDue: 850000,
    paymentAttention: 'upcoming',
    settlementMode: 'buyer-payment',
    eligibleReceivables: 1750000,
    availableToWithdraw: 650000,
    instalments: [],
    note: 'Buyer payment settles this Dynamic Period through the Client Clearing Account.',
  },
  {
    id: 'inf-fresh-overdue',
    reference: 'DP-2026-08-15-FRESH',
    relationshipId: 'inf-fresh',
    relationshipName: 'FreshProduce Kenya Ltd',
    relationshipType: 'Counterparty Buyer',
    ...financingStatus('overdue'),
    disbursementDate: '2026-07-02',
    repaymentDueDate: '2026-08-15',
    amountFinanced: 600000,
    totalRepaid: 150000,
    outstandingBalance: 450000,
    amountDue: 450000,
    paymentAttention: 'overdue',
    settlementMode: 'buyer-payment',
    eligibleReceivables: 900000,
    availableToWithdraw: 0,
    instalments: [],
  },
  {
    id: 'inf-fresh-repaid',
    reference: 'DP-2026-06-30-FRESH',
    relationshipId: 'inf-fresh',
    relationshipName: 'FreshProduce Kenya Ltd',
    relationshipType: 'Counterparty Buyer',
    ...financingStatus('repaid'),
    disbursementDate: '2026-06-04',
    repaymentDueDate: '2026-06-30',
    amountFinanced: 320000,
    totalRepaid: 320000,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'buyer-payment',
    eligibleReceivables: 500000,
    availableToWithdraw: 0,
    instalments: [],
  },
  {
    id: 'inf-fresh-cancelled',
    reference: 'DP-2026-09-30-FRESH',
    relationshipId: 'inf-fresh',
    relationshipName: 'FreshProduce Kenya Ltd',
    relationshipType: 'Counterparty Buyer',
    ...financingStatus('cancelled'),
    repaymentDueDate: '2026-09-30',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'buyer-payment',
    eligibleReceivables: 0,
    availableToWithdraw: 0,
    instalments: [],
  },
  {
    id: 'inf-fresh-declined',
    reference: 'DP-2026-11-15-FRESH',
    relationshipId: 'inf-fresh',
    relationshipName: 'FreshProduce Kenya Ltd',
    relationshipType: 'Counterparty Buyer',
    ...financingStatus('declined'),
    repaymentDueDate: '2026-11-15',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'buyer-payment',
    eligibleReceivables: 0,
    availableToWithdraw: 0,
    instalments: [],
  },
]

const INFX_PERIODS: readonly CustomerFinancingPeriod[] = [
  {
    id: 'infx-mombasa-requested',
    reference: 'FR-2026-0818',
    relationshipId: 'infx-mombasa',
    relationshipName: 'Mombasa Buyers Network',
    relationshipType: 'Approved Buyer',
    ...financingStatus('requested'),
    repaymentDueDate: '2026-10-02',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'INV-2026-0044',
    financedDays: 45,
    instalments: [],
  },
  {
    id: 'infx-kisumu-live',
    reference: 'FR-2026-0028',
    relationshipId: 'infx-kisumu',
    relationshipName: 'Kisumu Buyers Co-op',
    relationshipType: 'Approved Buyer',
    ...financingStatus('live'),
    disbursementDate: '2026-07-03',
    repaymentDueDate: '2026-09-02',
    amountFinanced: 900000,
    totalRepaid: 0,
    outstandingBalance: 900000,
    amountDue: 958650,
    paymentAttention: 'upcoming',
    settlementMode: 'manual',
    invoiceReference: 'INV-2026-0028',
    financedDays: 60,
    instalments: [],
  },
  {
    id: 'infx-mombasa-overdue',
    reference: 'FR-2026-0017',
    relationshipId: 'infx-mombasa',
    relationshipName: 'Mombasa Buyers Network',
    relationshipType: 'Approved Buyer',
    ...financingStatus('overdue'),
    disbursementDate: '2026-07-01',
    repaymentDueDate: '2026-08-01',
    amountFinanced: 510000,
    totalRepaid: 0,
    outstandingBalance: 510000,
    amountDue: 545190,
    paymentAttention: 'overdue',
    settlementMode: 'manual',
    invoiceReference: 'INV-2026-0017',
    financedDays: 30,
    instalments: [],
  },
  {
    id: 'infx-nairobi-repaid',
    reference: 'FR-2026-0009',
    relationshipId: 'infx-nairobi',
    relationshipName: 'Nairobi Retail Group',
    relationshipType: 'Approved Buyer',
    ...financingStatus('repaid'),
    disbursementDate: '2026-04-10',
    repaymentDueDate: '2026-05-25',
    amountFinanced: 400000,
    totalRepaid: 400000,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'INV-2026-0009',
    financedDays: 45,
    instalments: [],
  },
  {
    id: 'infx-nairobi-cancelled',
    reference: 'FR-2026-0729',
    relationshipId: 'infx-nairobi',
    relationshipName: 'Nairobi Retail Group',
    relationshipType: 'Approved Buyer',
    ...financingStatus('cancelled'),
    repaymentDueDate: '2026-09-12',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'INV-2026-0040',
    financedDays: 45,
    instalments: [],
  },
  {
    id: 'infx-nairobi-declined',
    reference: 'FR-2026-0805',
    relationshipId: 'infx-nairobi',
    relationshipName: 'Nairobi Retail Group',
    relationshipType: 'Approved Buyer',
    ...financingStatus('declined'),
    repaymentDueDate: '2026-09-19',
    amountFinanced: 0,
    totalRepaid: 0,
    outstandingBalance: 0,
    amountDue: 0,
    paymentAttention: null,
    settlementMode: 'manual',
    invoiceReference: 'INV-2026-0043',
    financedDays: 45,
    instalments: [],
  },
]

export const CUSTOMER_WORKSPACES: readonly CustomerWorkspace[] = [
  {
    id: 'acl',
    heading: 'Agri Credit Line',
    intro: 'Manage available credit, financing periods and repayment details from one workspace.',
    primaryActionLabel: 'Request funds',
    primaryActionKind: 'request-funds',
    relationshipNoun: 'financing period',
    availableMetricLabel: 'Available Credit',
    availableMetricValue: 1300000,
    availableMetricHelper: 'Ksh 1,200,000 currently used',
    outstandingMetricLabel: 'Outstanding Amount',
    outstandingMetricValue: 1200000,
    outstandingMetricHelper: 'Across unsettled Agri Credit Line financing',
    dueMetricLabel: 'Payments Due',
    dueActionLabel: 'View payments due',
    dueDateColumnLabel: 'Repayment Due Date',
    totalRepaidColumnLabel: 'Total Repaid',
    outstandingColumnLabel: 'Outstanding Balance',
    relationships: [],
    periods: ACL_PERIODS,
  },
  {
    id: 'abf',
    heading: 'Agri Buyer Financing',
    intro: 'See your Supplier limits, active financing periods and repayments without leaving the product workspace.',
    primaryActionLabel: 'Request funds',
    primaryActionKind: 'relationships',
    relationshipNavLabel: 'Suppliers',
    relationshipHeading: 'Approved Suppliers',
    relationshipIntro: 'Choose an approved Supplier to view financing availability or request funds.',
    relationshipNoun: 'Supplier',
    availableMetricLabel: 'Available Credit',
    availableMetricValue: 1741000,
    availableMetricHelper: 'Subject to Supplier sub-limits',
    outstandingMetricLabel: 'Outstanding Amount',
    outstandingMetricValue: 649000,
    outstandingMetricHelper: 'Across active ABF financing periods',
    dueMetricLabel: 'Payments Due',
    dueActionLabel: 'View payments due',
    dueDateColumnLabel: 'Repayment Due Date',
    totalRepaidColumnLabel: 'Total Repaid',
    outstandingColumnLabel: 'Outstanding Balance',
    relationships: [
      {
        id: 'abf-quickmart',
        name: 'Quick Mart Stores',
        relationshipType: 'Counterparty Supplier',
        limitLabel: 'Supplier sub-limit',
        limit: 900000,
        used: 380000,
        available: 520000,
        periodIds: ['abf-quickmart-live', 'abf-quickmart-repaid'],
        fundsRequestUrl: ABF_FUNDS_REQUEST_DEMO_URL,
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
      {
        id: 'abf-naivas',
        name: 'Naivas Fresh Produce',
        relationshipType: 'Counterparty Supplier',
        limitLabel: 'Supplier sub-limit',
        limit: 1500000,
        used: 459000,
        available: 1041000,
        periodIds: ['abf-naivas-overdue', 'abf-naivas-cancelled'],
        fundsRequestUrl: ABF_FUNDS_REQUEST_DEMO_URL,
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
      {
        id: 'abf-eastleigh',
        name: 'Eastleigh Traders Co.',
        relationshipType: 'Counterparty Supplier',
        limitLabel: 'Supplier sub-limit',
        limit: 600000,
        used: 0,
        available: 600000,
        periodIds: ['abf-eastleigh-requested', 'abf-eastleigh-declined'],
        fundsRequestUrl: ABF_FUNDS_REQUEST_DEMO_URL,
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
    ],
    periods: ABF_PERIODS,
  },
  {
    id: 'stf',
    heading: 'Stockist Financing',
    intro: 'Manage Partner Supplier limits, financing periods and repayments from one Stockist workspace.',
    primaryActionLabel: 'Request funds',
    primaryActionKind: 'relationships',
    relationshipNavLabel: 'Partner Suppliers',
    relationshipHeading: 'Partner Suppliers',
    relationshipIntro: 'Choose a Partner Supplier to view financing availability or request funds.',
    relationshipNoun: 'Partner Supplier',
    availableMetricLabel: 'Available Financing',
    availableMetricValue: 980000,
    availableMetricHelper: 'Across approved Partner Supplier sub-limits',
    outstandingMetricLabel: 'Outstanding Amount',
    outstandingMetricValue: 390000,
    outstandingMetricHelper: 'Across active Stockist Financing periods',
    dueMetricLabel: 'Payments Due',
    dueActionLabel: 'View payments due',
    dueDateColumnLabel: 'Repayment Due Date',
    totalRepaidColumnLabel: 'Total Repaid',
    outstandingColumnLabel: 'Outstanding Balance',
    relationships: [
      {
        id: 'stf-greenharvest',
        name: 'GreenHarvest Distributors',
        relationshipType: 'Partner Supplier',
        limitLabel: 'Partner Supplier sub-limit',
        limit: 900000,
        used: 300000,
        available: 600000,
        periodIds: ['stf-greenharvest-requested', 'stf-greenharvest-live'],
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
      {
        id: 'stf-meru',
        name: 'Meru Agrovets Ltd',
        relationshipType: 'Partner Supplier',
        limitLabel: 'Partner Supplier sub-limit',
        limit: 450000,
        used: 240000,
        available: 210000,
        periodIds: ['stf-meru-overdue', 'stf-meru-cancelled'],
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
      {
        id: 'stf-seedco',
        name: 'SeedCo Kenya',
        relationshipType: 'Partner Supplier',
        limitLabel: 'Partner Supplier sub-limit',
        limit: 680000,
        used: 0,
        available: 680000,
        periodIds: ['stf-seedco-repaid', 'stf-seedco-declined'],
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
    ],
    periods: STF_PERIODS,
  },
  {
    id: 'invoice-financing',
    heading: 'Invoice Financing',
    intro: 'Manage Buyer relationships and Dynamic Periods from the Client Supplier perspective.',
    primaryActionLabel: 'Request funds',
    primaryActionKind: 'relationships',
    relationshipNavLabel: 'Buyers',
    relationshipHeading: 'Buyer Relationships',
    relationshipIntro: 'Choose a Buyer. Upload invoices where you are responsible, or request funds from an eligible Dynamic Period.',
    relationshipNoun: 'Buyer',
    availableMetricLabel: 'Available to Withdraw',
    availableMetricValue: 970000,
    availableMetricHelper: 'Across eligible Dynamic Periods',
    outstandingMetricLabel: 'Outstanding Amount',
    outstandingMetricValue: 1300000,
    outstandingMetricHelper: 'Settled from Buyer payments',
    dueMetricLabel: 'Settlements Due',
    dueActionLabel: 'View periods due',
    dueDateColumnLabel: 'Period Due Date',
    totalRepaidColumnLabel: 'Buyer Payments Allocated',
    outstandingColumnLabel: 'Outstanding Amount',
    relationships: [
      {
        id: 'inf-twiga',
        name: 'Twiga Foods Ltd',
        relationshipType: 'Partner Buyer',
        limitLabel: 'Buyer sub-limit',
        limit: 1500000,
        used: 850000,
        available: 650000,
        periodIds: ['inf-twiga-requested', 'inf-twiga-live'],
        invoiceUploadOwner: 'partner-buyer',
      },
      {
        id: 'inf-fresh',
        name: 'FreshProduce Kenya Ltd',
        relationshipType: 'Counterparty Buyer',
        limitLabel: 'Buyer sub-limit',
        limit: 2000000,
        used: 450000,
        available: 1550000,
        periodIds: ['inf-fresh-overdue', 'inf-fresh-repaid', 'inf-fresh-cancelled', 'inf-fresh-declined'],
        invoiceUploadOwner: 'client',
      },
    ],
    periods: INF_PERIODS,
  },
  {
    id: 'infx',
    heading: 'Invoice Financing Express',
    intro: 'Manage approved Buyers, one-invoice financing periods and direct repayments to Avenews.',
    primaryActionLabel: 'Request funds',
    primaryActionKind: 'relationships',
    relationshipNavLabel: 'Buyers',
    relationshipHeading: 'Approved Buyers',
    relationshipIntro: 'Choose an approved Buyer to view financing availability or request funds for an invoice.',
    relationshipNoun: 'Buyer',
    availableMetricLabel: 'Available Credit',
    availableMetricValue: 1070000,
    availableMetricHelper: 'Subject to approved Buyer sub-limits',
    outstandingMetricLabel: 'Outstanding Amount',
    outstandingMetricValue: 1410000,
    outstandingMetricHelper: 'Across active Invoice Financing Express periods',
    dueMetricLabel: 'Payments Due',
    dueActionLabel: 'View payments due',
    dueDateColumnLabel: 'Repayment Due Date',
    totalRepaidColumnLabel: 'Total Repaid',
    outstandingColumnLabel: 'Outstanding Balance',
    relationships: [
      {
        id: 'infx-kisumu',
        name: 'Kisumu Buyers Co-op',
        relationshipType: 'Approved Buyer',
        limitLabel: 'Buyer sub-limit',
        limit: 900000,
        used: 900000,
        available: 0,
        periodIds: ['infx-kisumu-live'],
        fundsRequestEnabled: false,
        fundsRequestLabel: 'Sub-limit fully used',
      },
      {
        id: 'infx-mombasa',
        name: 'Mombasa Buyers Network',
        relationshipType: 'Approved Buyer',
        limitLabel: 'Buyer sub-limit',
        limit: 600000,
        used: 510000,
        available: 90000,
        periodIds: ['infx-mombasa-requested', 'infx-mombasa-overdue'],
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
      {
        id: 'infx-nairobi',
        name: 'Nairobi Retail Group',
        relationshipType: 'Approved Buyer',
        limitLabel: 'Buyer sub-limit',
        limit: 700000,
        used: 0,
        available: 700000,
        periodIds: ['infx-nairobi-repaid', 'infx-nairobi-cancelled', 'infx-nairobi-declined'],
        fundsRequestEnabled: true,
        fundsRequestLabel: 'Request funds',
      },
    ],
    periods: INFX_PERIODS,
  },
]

export function customerWorkspaceById(id: string | null | undefined): CustomerWorkspace | undefined {
  return CUSTOMER_WORKSPACES.find(workspace => workspace.id === id)
}

export function periodsForRelationship(
  workspace: CustomerWorkspace,
  relationship: CustomerRelationship,
): readonly CustomerFinancingPeriod[] {
  return workspace.periods.filter(period => relationship.periodIds.includes(period.id))
}

export function paymentAttentionCounts(workspace: CustomerWorkspace): { overdue: number; upcoming: number; total: number } {
  const overdue = workspace.periods.filter(period => period.paymentAttention === 'overdue').length
  const upcoming = workspace.periods.filter(period => period.paymentAttention === 'upcoming').length
  return { overdue, upcoming, total: overdue + upcoming }
}
