import { test, expect, type Page, type Locator } from '@playwright/test'

const supplierHome='/experience/invoice-financing/home'
const partnerHome='/experience/invoice-partner/home'
const errors=new WeakMap<Page,string[]>()
const invoiceFile={name:'my-review-invoice.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nreview invoice sample')}
const deliveryFile={name:'my-delivery-proof.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nreview delivery sample')}

function rows(root:Locator):Locator{return root.locator('table.review-table tbody tr:visible, article.mobile-record:visible')}
async function search(root:Locator,text:string){await root.locator('input[type="search"]:visible').fill(text)}
async function selectControl(page:Page,root:Locator,label:string,value:string){
  if((page.viewportSize()?.width??1440)<768){
    await root.getByRole('button',{name:'Filters',exact:true}).click()
    await root.locator('select[aria-label="'+label+'"]:visible').selectOption(value)
    await root.getByRole('button',{name:'Apply',exact:true}).click()
  }else await root.locator('select[aria-label="'+label+'"]').selectOption(value)
}
async function geometry(page:Page){
  const bounds=await page.evaluate(()=>({viewport:window.innerWidth,width:document.documentElement.scrollWidth,
    dialogs:[...document.querySelectorAll<HTMLDialogElement>('dialog[open]')].map(d=>({left:d.getBoundingClientRect().left,right:d.getBoundingClientRect().right,top:d.getBoundingClientRect().top,bottom:d.getBoundingClientRect().bottom})),height:window.innerHeight}))
  expect(bounds.width).toBeLessThanOrEqual(bounds.viewport+2)
  for(const d of bounds.dialogs){expect(d.left).toBeGreaterThanOrEqual(-1);expect(d.right).toBeLessThanOrEqual(bounds.viewport+1);expect(d.top).toBeGreaterThanOrEqual(-1);expect(d.bottom).toBeLessThanOrEqual(bounds.height+1)}
}
async function openPeriod(page:Page,reference:string,partner=false){
  const table=page.locator('app-review-period-table').first()
  await search(table,reference)
  await rows(table).first().getByRole('button',{name:partner?'View payment':'View',exact:true}).click()
  await expect(page.locator('dialog[open]')).toHaveCount(1)
  return page.locator('dialog[open]')
}

test.beforeEach(async({page})=>{
  const issues:string[]=[];errors.set(page,issues);page.on('pageerror',error=>issues.push(error.message))
  await page.addInitScript(()=>{
    localStorage.setItem('av_customer_portal_session',JSON.stringify({contactId:'usr_review',contactFirstName:'Demo',contactLastName:'Reviewer',contactEmail:'reviewer@example.test',businessId:'biz_demo_001',businessName:'Kioko Agri Supplies Ltd',role:'admin'}))
  })
})
test.afterEach(async({page})=>{expect(errors.get(page)??[]).toEqual([])})

test('supplier home reconciles credit and filters outstanding disbursed periods',async({page},testInfo)=>{
  await page.goto(supplierHome)
  const content=page.locator('[data-invoice-review-role="supplier"]')
  await expect(content.getByRole('heading',{name:'Invoice Financing',exact:true})).toBeVisible()
  const cards=content.locator('.review-metrics .review-card')
  await expect(cards.nth(0)).toContainText('320,000')
  await expect(cards.nth(0)).toContainText('3,000,000')
  await expect(cards.nth(1)).toContainText('1,300,000')
  await expect(content.locator('.review-explainer')).toContainText('292,000')
  await expect(content.locator('.review-explainer')).toContainText('1,408,000')
  await expect(page.getByRole('link',{name:'Invoices',exact:true})).toBeVisible()
  await expect(page.getByText('Invoice Uploader',{exact:true})).toHaveCount(0)
  await content.getByRole('button',{name:'About Total approved limit',exact:true}).click()
  await expect(page.getByRole('tooltip')).toContainText('not the sum of buyer sub-limits')
  await content.getByRole('heading',{name:'Invoice Financing',exact:true}).click()
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('supplier-home.png'),fullPage:true})
  await content.getByRole('button',{name:'View outstanding periods',exact:true}).click()
  const table=content.locator('app-review-period-table')
  await expect(rows(table)).toHaveCount(2)
  await expect(table).toContainText('DP-2026-09-15-TWIGA')
  await expect(table).toContainText('DP-2026-08-15-FRESH')
  await expect(table).not.toContainText('DP-2026-10-15-TWIGA')
  await content.getByRole('button',{name:'Show all',exact:true}).click()
  await expect(rows(table)).toHaveCount(6)
  await content.getByRole('button',{name:'View available periods',exact:true}).click()
  await expect(rows(table)).toHaveCount(1)
  await expect(table).toContainText('DP-2026-10-15-TWIGA')
})

test('supplier period invoice tab reuses exact records and preserves Files',async({page},testInfo)=>{
  await page.goto(supplierHome)
  const modal=await openPeriod(page,'DP-2026-09-15-TWIGA')
  await expect(modal.getByRole('tab',{name:'Overview',exact:true})).toHaveAttribute('aria-selected','true')
  await modal.getByRole('tab',{name:'Invoices (2)',exact:true}).click()
  const invoices=modal.locator('app-review-invoices')
  await expect(rows(invoices)).toHaveCount(2)
  await expect(invoices).toContainText('INV-7811')
  await expect(invoices).toContainText('INV-7812')
  await expect(invoices).not.toContainText('INV-9120')
  await expect(invoices.getByRole('link',{name:'View invoice',exact:true})).toHaveCount(2)
  await selectControl(page,invoices,'Sort by','amount:asc')
  await expect(rows(invoices).first()).toContainText('INV-7812')
  await search(invoices,'not-an-invoice')
  await expect(invoices.getByText('No matching records',{exact:true})).toBeVisible()
  await search(invoices,'')
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('supplier-period-invoices.png'),fullPage:true})
  await modal.getByRole('tab',{name:'Invoices (2)',exact:true}).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(modal.getByRole('tab',{name:'Overview',exact:true})).toBeFocused()
  await modal.getByRole('button',{name:'Files',exact:true}).click()
  await expect(modal.getByRole('link',{name:'View PDF',exact:true})).toHaveAttribute('href','/demo-documents/funds-request-snapshot-demo.pdf')
  await modal.getByRole('button',{name:'Back to period',exact:false}).click()
  await modal.getByRole('button',{name:'Close dialog',exact:true}).click()
  await expect(page.locator('dialog[open]')).toHaveCount(0)
})

test('invoice rows without files remain visible and empty period keeps its Invoices tab',async({page})=>{
  await page.goto(supplierHome)
  let modal=await openPeriod(page,'DP-2026-10-15-TWIGA')
  await modal.getByRole('tab',{name:'Invoices (1)',exact:true}).click()
  await expect(modal.locator('app-review-invoices')).toContainText('DEMO-TWIGA-1015')
  await expect(modal.getByRole('link',{name:'View invoice',exact:true})).toHaveCount(0)
  await modal.getByRole('button',{name:'Close dialog',exact:true}).click()
  modal=await openPeriod(page,'DP-2026-11-15-FRESH')
  await modal.getByRole('tab',{name:'Invoices (0)',exact:true}).click()
  await expect(modal.getByText('No invoices linked to this period',{exact:true})).toBeVisible()
  await geometry(page)
})

test('ownership chooser and buyer relationship terms are explicit',async({page},testInfo)=>{
  await page.goto(supplierHome)
  await page.locator('.review-hero').getByRole('button',{name:'Upload invoices',exact:true}).click()
  let modal=page.locator('dialog[open]')
  await expect(modal.getByRole('heading',{name:'Who uploads your invoices?',exact:true})).toBeVisible()
  await expect(modal.getByText('Buyer uploads invoices',{exact:true})).toBeVisible()
  await expect(modal.getByText('You upload invoices',{exact:true})).toBeVisible()
  await expect(modal.getByRole('button',{name:'Upload for Twiga Foods Ltd',exact:true})).toHaveCount(0)
  await expect(modal.getByRole('button',{name:'Upload for FreshProduce Kenya Ltd',exact:true})).toBeVisible()
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('upload-ownership-chooser.png'),fullPage:true})
  await modal.getByRole('button',{name:'Close dialog',exact:true}).click()
  await page.goto('/experience/invoice-financing/financing')
  const table=page.locator('app-review-table').first()
  await expect(table).toContainText('Buyer uploads invoices')
  await expect(table).toContainText('You upload invoices')
  await search(table,'Twiga')
  await rows(table).first().getByRole('button',{name:'View details',exact:true}).click()
  modal=page.locator('dialog[open]')
  await expect(modal).toContainText('Relationship terms')
  await expect(modal).toContainText('0.17%')
  await expect(modal).toContainText('85%')
  await expect(modal).not.toContainText('Your rebate rate')
  await modal.getByRole('button',{name:/View financing periods/}).click()
  await expect(rows(modal.locator('app-review-period-table'))).toHaveCount(2)
  await geometry(page)
})

test('native uploader validates sections, POD, declaration and retains a review receipt',async({page},testInfo)=>{
  await page.goto(supplierHome)
  await page.locator('.review-hero').getByRole('button',{name:'Upload invoices',exact:true}).click()
  await page.getByRole('button',{name:'Upload for FreshProduce Kenya Ltd',exact:true}).click()
  const modal=page.locator('dialog[open]')
  await modal.getByRole('button',{name:'Save review upload',exact:true}).click()
  await expect(modal.locator('[role="alert"]').first()).toContainText('due date')
  const first=modal.locator('section.review-group').first()
  await first.locator('input[type="date"]').fill('2026-09-30')
  await first.locator('input[id$="-files"]').setInputFiles(invoiceFile)
  await modal.getByRole('button',{name:'Save review upload',exact:true}).click()
  await expect(modal.locator('[role="alert"]').first()).toContainText('Proof of Delivery')
  await first.locator('input[id$="-pod"]').setInputFiles(deliveryFile)
  await modal.getByRole('button',{name:'Copy section 1',exact:true}).click()
  const second=modal.locator('section.review-group').nth(1)
  await second.locator('input[id$="-files"]').setInputFiles({...invoiceFile,name:'second-review.pdf'})
  await second.locator('input[id$="-pod"]').setInputFiles(deliveryFile)
  await modal.getByRole('checkbox').check()
  await modal.getByRole('button',{name:'Save review upload',exact:true}).click()
  await expect(modal.locator('[role="alert"]').first()).toContainText('merge sections')
  await modal.getByRole('button',{name:'Delete section 2',exact:true}).click()
  await modal.getByRole('button',{name:'Save review upload',exact:true}).click()
  await expect(modal.locator('[role="alert"]').first()).toContainText('Confirm')
  await modal.getByRole('checkbox').check()
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('native-upload-form.png'),fullPage:true})
  await modal.getByRole('button',{name:'Save review upload',exact:true}).click()
  await expect(modal.getByText('Review upload saved',{exact:true})).toBeVisible()
  await expect(modal).toContainText('Nothing has been sent to Avenews')
  await expect(modal).toContainText('Demo Reviewer')
  await modal.getByRole('button',{name:'View invoices',exact:true}).click()
  await expect(page).toHaveURL(/\/experience\/invoice-financing\/invoices$/)
  const invoices=page.locator('app-review-invoices')
  await search(invoices,'my-review-invoice')
  await expect(rows(invoices)).toHaveCount(1)
  await expect(rows(invoices).first()).toContainText('Pending review')
  await expect(rows(invoices).first().getByRole('link',{name:'View invoice',exact:true})).toHaveAttribute('href',/^blob:/)
  await page.getByRole('tab',{name:'Upload history (1)',exact:true}).click()
  await page.getByRole('button',{name:'View receipt',exact:true}).click()
  await expect(page.locator('dialog[open]')).toContainText('my-delivery-proof.pdf')
  await expect(page.locator('dialog[open]')).toContainText('usr_review')
})

test('review request updates shared availability but not disbursed outstanding',async({page})=>{
  await page.goto(supplierHome)
  const table=page.locator('app-review-period-table')
  await search(table,'DP-2026-10-15-TWIGA')
  await rows(table).first().getByRole('button',{name:'Request funds',exact:true}).click()
  const modal=page.locator('dialog[open]')
  await modal.locator('#review-request-amount').fill('50000')
  await modal.getByRole('button',{name:'Save review request',exact:true}).click()
  await expect(modal).toContainText('Review request saved')
  await expect(modal).toContainText('not changed')
  await modal.getByRole('button',{name:'Close dialog',exact:true}).click()
  const cards=page.locator('.review-metrics .review-card')
  await expect(cards.nth(0)).toContainText('270,000')
  await expect(cards.nth(1)).toContainText('1,300,000')
  await expect(page.locator('.review-explainer')).toContainText('342,000')
})

test('partner home hosts payments and reconciles supplier rebates',async({page},testInfo)=>{
  await page.goto(partnerHome)
  const content=page.locator('[data-invoice-review-role="partner"]')
  await expect(content.getByRole('heading',{name:'Partner Buyer Portal',exact:true})).toBeVisible()
  await expect(content.getByRole('heading',{name:'Supplier payments',exact:true})).toBeVisible()
  await expect(content.locator('.review-metrics .review-card').first()).toContainText('2,600')
  await expect(content.locator('.partner-home-workspace-card')).toHaveCount(0)
  await expect(content).not.toContainText('Available financing')
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('partner-home.png'),fullPage:true})
  await content.getByRole('button',{name:'View rebate breakdown',exact:true}).click()
  const modal=page.locator('dialog[open]')
  await expect(modal).toContainText('Total rebate due')
  await expect(modal).toContainText('2,600')
  const table=modal.locator('app-review-table')
  await search(table,'Coastline')
  const coast=rows(table).first()
  await expect(coast).toContainText('150,000')
  await expect(coast).toContainText('1,500')
  await expect(coast).toContainText('500')
  await expect(coast).toContainText('1,000')
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('partner-rebates.png'),fullPage:true})
  await coast.getByRole('button',{name:'View supplier',exact:true}).click()
  await expect(page.locator('dialog[open]')).toContainText('Your rebate rate')
  await expect(page.locator('dialog[open]')).not.toContainText('Daily markup')
  await expect(page.locator('dialog[open]')).not.toContainText('Buyer sub-limit')
})

test('partner payment details show full balance, designated account and period invoices',async({page},testInfo)=>{
  await page.goto(partnerHome)
  const modal=await openPeriod(page,'PER-2026-08-15-COAST',true)
  await expect(modal.locator('.review-metric-value')).toContainText('890,000')
  await expect(modal).toContainText('DEMO-COAST')
  await expect(modal).toContainText('do not pay')
  await modal.getByRole('button',{name:'Copy account number',exact:true}).click()
  await expect(modal.locator('[role="status"]')).toContainText(/copied|Copy was blocked/)
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('partner-payment-details.png'),fullPage:true})
  await modal.getByRole('tab',{name:'Invoices (9)',exact:true}).click()
  const invoices=modal.locator('app-review-invoices')
  await expect(rows(invoices)).toHaveCount(9)
  await expect(invoices).toContainText('DEMO-COAST-1')
  await expect(invoices).not.toContainText('DEMO-NAIROBI')
  await expect(invoices.getByRole('link',{name:'View invoice',exact:true})).toHaveCount(0)
  await geometry(page)
  await page.screenshot({path:testInfo.outputPath('partner-period-invoices.png'),fullPage:true})
  await modal.getByRole('button',{name:'Close dialog',exact:true}).click()
  await page.goto('/experience/invoice-partner/obligations')
  const table=page.locator('app-review-period-table')
  await search(table,'PER-2026-08-15-COAST')
  await expect(rows(table).first()).toContainText('890,000')
  await expect(page.locator('.review-hero .page-eyebrow')).toHaveCount(0)
})

test('missing clearing account is explicit and payment methods are relationship-specific',async({page})=>{
  await page.goto(partnerHome)
  let modal=await openPeriod(page,'PER-2026-10-10-ELDORET',true)
  await expect(modal).toContainText('Clearing-account details are not available yet')
  await expect(modal.getByRole('button',{name:'Copy account number',exact:true})).toHaveCount(0)
  await modal.getByRole('button',{name:'Close dialog',exact:true}).click()
  modal=await openPeriod(page,'DP-2026-09-15-TWIGA',true)
  await modal.getByRole('tab',{name:'M-Pesa Paybill',exact:true}).click()
  await expect(modal).toContainText('DEMO-PAYBILL')
  await expect(modal).toContainText('DEMO-KIOKO')
  await expect(modal).not.toContainText('2046346095')
  await geometry(page)
})

test('invoice lists retain no-file records with shared sorting, filtering and pagination',async({page})=>{
  await page.goto('/experience/invoice-partner/invoice-uploads')
  const invoices=page.locator('app-review-invoices')
  await expect(rows(invoices)).toHaveCount(10)
  await invoices.getByRole('button',{name:'Next page',exact:true}).click()
  await expect(invoices).toContainText('Page 2')
  await search(invoices,'DEMO-TWIGA-1015')
  await expect(rows(invoices)).toHaveCount(1)
  await expect(invoices.getByRole('link',{name:'View invoice',exact:true})).toHaveCount(0)
  await search(invoices,'')
  await selectControl(page,invoices,'Status','Paid')
  await expect(rows(invoices)).toHaveCount(2)
  await expect(rows(invoices).first()).toContainText('DEMO-MAKUENI')
  await geometry(page)
})

test('partner upload form accepts approved supplier selection and an unparsed bulk file',async({page})=>{
  await page.goto(partnerHome)
  await page.locator('.review-hero').getByRole('button',{name:'Upload invoices',exact:true}).click()
  const modal=page.locator('dialog[open]')
  await modal.locator('select[id$="-relationship"]').selectOption('inf-twiga')
  await modal.locator('input[type="date"]').fill('2026-10-15')
  await expect(modal.locator('input[id$="-pod"]')).toHaveCount(0)
  await modal.locator('input[id$="-files"]').setInputFiles({name:'review-supplier-export.csv',mimeType:'text/csv',buffer:Buffer.from('invoice,amount\nINV-REVIEW,1000')})
  await modal.getByRole('checkbox').check()
  await modal.getByRole('button',{name:'Save review upload',exact:true}).click()
  await expect(modal).toContainText('Review upload saved')
  await modal.getByRole('button',{name:'View invoices',exact:true}).click()
  const invoices=page.locator('app-review-invoices')
  await search(invoices,'review-supplier-export')
  await expect(rows(invoices).first()).toContainText('Review upload')
  await expect(rows(invoices).first()).toContainText('Pending review')
})

test('other customer product homes still render their original components',async({page})=>{
  for(const [id,heading] of [['acl','Agri Credit Line'],['abf','Agri Buyer Financing'],['stf','Stockist Financing'],['infx','Invoice Financing Express']]){
    await page.goto(`/experience/${id}/home`)
    await expect(page.locator('app-contextual-home')).toBeVisible()
    await expect(page.locator('app-contextual-home h1')).toHaveText(heading)
    await expect(page.locator('app-invoice-review-page')).toHaveCount(0)
    await geometry(page)
  }
})
