import { test, expect, type Page } from '@playwright/test'
const session = {contactId:'usr_001',contactFirstName:'Amara',contactLastName:'Osei',contactEmail:'amara@example.test',businessId:'biz_demo_001',businessName:'Kioko Agri Supplies Ltd',role:'admin'}
async function painted(page:Page) { await page.evaluate(async()=>{await document.fonts.ready;await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())))}) }
test('visible modal content and bounded dropdown in the actual viewport',async({page},info)=>{
  await page.addInitScript(value=>localStorage.setItem('av_customer_portal_session',JSON.stringify(value)),session)
  await page.goto('/experience/invoice-financing/home')
  await expect(page.getByRole('heading',{name:'Invoice Financing',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Upload invoices',exact:true}).click()
  let modal=page.getByRole('dialog')
  const selector=modal.getByRole('combobox')
  await selector.fill('FreshProduce')
  await modal.getByRole('option').filter({hasText:'FreshProduce'}).click()
  await modal.locator('.party-select__toggle').click()
  const list=modal.getByRole('listbox')
  await expect(list).toBeVisible()
  const rectangle=await list.boundingBox(),viewport=page.viewportSize()!
  expect(rectangle!.y).toBeGreaterThanOrEqual(0)
  expect(rectangle!.y+rectangle!.height).toBeLessThanOrEqual(viewport.height)
  expect(rectangle!.x).toBeGreaterThanOrEqual(0)
  expect(rectangle!.x+rectangle!.width).toBeLessThanOrEqual(viewport.width)
  await expect(modal.locator('.party-select__hint')).toBeVisible()
  await painted(page)
  await page.screenshot({path:info.outputPath('uploader-dropdown-viewport.png')})
  await selector.press('Escape')
  await modal.getByRole('button',{name:'Close',exact:true}).click()
  const row=page.locator('.customer-activity-table tbody tr:visible,.customer-activity-cards .customer-financing-card:visible').filter({hasText:'DP-2026-08-15-FRESH'})
  await row.click()
  await page.getByRole('dialog').getByRole('button',{name:'Payment details',exact:true}).click()
  modal=page.getByRole('dialog')
  await expect(modal.getByRole('button',{name:'Back',exact:true})).toBeVisible()
  await expect(modal.locator('.customer-settlement-card')).toBeVisible()
  await expect(modal.getByText('Your Avenews Clearing Account',{exact:true})).toBeVisible()
  await painted(page)
  await page.screenshot({path:info.outputPath('payment-details-viewport.png')})
  await modal.getByRole('button',{name:'Back',exact:true}).click()
  await expect(page.getByRole('dialog').locator('.customer-overdue--buyer')).toBeVisible()
})
